// Product catalogue. Facts are taken verbatim from the product pages on
// new.belach.se; wording is lightly normalised (units, chemical formulae,
// bullet style, obvious typos) and every product now uses the same structure.
//
//   meta      four key facts shown under the product hero
//   specs     specification table rows [label, value]
//   sections  ordered content blocks: { title, text } | { title, items: [] }
//   old       the product's URL on the current site (use for 301 redirects)
//   draft     true = kept in the data but not published (needs a decision)

export const productCategories = [
  {
    id: 'bioreactors',
    title: 'Bioreactors',
    kicker: '0.2 – 1000 L',
    intro: 'Belach Bioteknik provides high-performance, custom-engineered bioreactor systems for FoodTech (including cultured meat), human and veterinary pharmaceuticals, vaccine production and industrial fermentation. We deliver comprehensive solutions through basic design and detailed engineering, ensuring each system is built to the user’s precise requirements.',
    note: 'All systems use magnetic coupling (top or bottom-mounted) for a hermetically sealed environment, eliminating contamination risks and maintaining the highest sterility standards.',
  },
  {
    id: 'decontamination',
    title: 'Decontamination systems',
    kicker: 'BSL 1 – 3',
    intro: 'Belach Bioteknik AB provides advanced Effluent Decontamination Systems (EDS) to safely treat bio-hazardous liquid waste from biocontainment facilities, hospitals, research laboratories, animal holding facilities and autopsy units. Our systems ensure complete inactivation of all viable microorganisms before discharge.',
    note: 'Batch-based heat treatment at 120–140 °C with user-defined holding times, followed by controlled cooling. F₀ cycle monitoring guarantees effective sterilization. Only electricity and water are required.',
  },
  {
    id: 'control',
    title: 'Bioprocess control systems',
    kicker: 'BioPhantom©',
    intro: 'Belach Bioteknik AB has developed BioPhantom©, an open bioreactor control system fully embracing PC-based digital control. Designed in close collaboration with end-users, it is tailored to the specific needs of fermentation experts and designed for use in GMP and GAMP environments.',
    note: 'Same platform for lab-scale, pilot and production bioreactors, ensuring smooth scale-up.',
  },
  {
    id: 'rental',
    title: 'Bioreactor rental',
    kicker: '10 – 100 L',
    intro: 'Use a Belach bioreactor on your own site for a specific period in exchange for set payments, without a large down payment.',
    note: 'The bioreactors are not newly manufactured; they are equipped with new instruments and tested before being handed over for operation.',
  },
];

export const products = [
  /* ---------------- bioreactors ---------------- */
  {
    slug: 'sterilizable-stainless-steel-bioreactors',
    old: 'https://new.belach.se/product/in-situ-bioreactors/',
    category: 'bioreactors',
    name: 'Sterilizable stainless-steel bioreactors',
    headline: 'For cell or microbial cultivation',
    figure: '5–1000 L',
    card: 'In-situ steam-sterilizable stainless-steel bioreactors for cell or microbial cultivation.',
    image: 'inSitu',
    gallery: ['inSitu', 'inSitu2', 'inSitu3', 'inSitu4'],
    meta: [['Working volume', '5–1000 L'], ['Vessel', 'Stainless steel'], ['Sterilization', 'In situ, steam (SIP)'], ['Control', 'BioPhantom©']],
    intro: [
      'High-grade stainless-steel systems engineered for SIP (sterilize-in-place). These plants are optimized for the complex requirements of the pharmaceutical and food industries, supporting stable, large-scale production.',
    ],
    specs: [
      ['Vessel', 'Stainless-steel bioreactor vessels, 5–1000 L working volume. Stainless-steel lid with 12 standard Pg13.5 instrument ports'],
      ['Control tower', 'One control tower for each bioreactor, including all electronic components, 3 peristaltic pumps on the front, utility and instrument connections on the back for easy accessibility and cable/hose management'],
      ['Stirrer', 'Hygienic bottom magnetic coupled stirrer, providing safer sterility. Rushton or pitch blade impeller, propeller'],
      ['Aeration', 'Applicable for aerobic/anaerobic cultivation, mass flow controlled, sterile filtered, off-gas cooling'],
      ['Temperature control', 'Electrical heating band, cooling finger'],
      ['Control', 'Stirrer speed, temperature, feeding rate, pH (by acid/base or CO₂), DO (by stirring, gas flow or feeding), antifoam/level'],
      ['Measurement', 'Exhaust gas analysis (O₂/CO₂), OD measurement'],
      ['Modules', 'Mass flow control of gas mix (air/O₂/CO₂), speed-controlled peristaltic pumps for feeding, on-off pumps for adding acid/base or antifoam, balance(s) for feed control'],
      ['Cleaning', 'Manual'],
      ['Sterilization', 'In-situ sterilizable with steam'],
      ['Software', 'BioPhantom© control software'],
    ],
    sections: [
      { title: 'Fields of application', items: ['Human and veterinary pharmaceuticals', 'Vaccines', 'Cultured meat', 'Food and beverage', 'Agriculture', 'Animal health and nutrition'], text: 'In research and development and at production scale.' },
    ],
  },
  {
    slug: 'pilot-and-production-bioreactors',
    old: 'https://new.belach.se/product/pilot-bioreactors-systems/',
    category: 'bioreactors',
    name: 'Pilot & production bioreactor systems',
    headline: 'Flexible, reliable, fully automated',
    figure: '10–1000 L',
    card: 'Stainless-steel, in-situ sterilizable systems that take your process from concept to commercial production.',
    image: 'pilot',
    gallery: ['pilot', 'photo300L', 'pilot2', 'photoProduction'],
    meta: [['Working volume', '10–1000 L'], ['Type', 'Stainless steel'], ['Sterilization', 'In situ'], ['Control', 'BioPhantom©']],
    intro: [
      'Take your biological processes from concept to commercial production with Belach Bioteknik’s pilot and production bioreactors, engineered for small and mid-sized companies, R&D teams and pilot-scale operations.',
    ],
    specs: [
      ['Volumes', '10–1000 L'],
      ['Type', 'Stainless steel, in-situ sterilizable'],
      ['Stirrer', 'Bottom-mounted magnetic stirrer for cells or microbes at every scale'],
      ['Integrated', 'Thermo-control, sterile filters and load cells'],
      ['Controlled parameters', 'Stirrer speed, level, temperature, DO, pH, redox, pressure, gas flow and feed pumps'],
      ['Options', 'Gas mixing station, gas analyzer or turbidity sensor; integration of 3rd-party instruments, sensors and equipment'],
    ],
    sections: [
      { title: 'Why our bioreactors stand out', items: [
        '<strong>Fully automated with BioPhantom©:</strong> complete automation for precise control and reproducible results.',
        '<strong>Flexible and powerful:</strong> bottom-mounted magnetic stirrer ensures perfect mixing for cells or microbes at every scale.',
        '<strong>Fully integrated stainless-steel system:</strong> thermo-control, sterile filters and load cells built in for safe, reliable operation.',
        '<strong>Precision process control:</strong> fine-tune stirrer speed, level, temperature, DO, pH, redox, pressure, gas flow and feed pumps with ease.',
        '<strong>Expandable and compatible:</strong> easily integrate 3rd-party instruments, sensors and equipment. Optional gas mixing station, gas analyzer or turbidity sensor for extra monitoring power.',
      ] },
      { title: 'Proven in real-world applications', text: 'From vaccine production to probiotic starter cultures, yeast fermentation and mammalian cell cultivation, our systems deliver consistent, scalable results.' },
      { title: 'Made for small and mid-sized companies', text: 'Get all the reliability of commercial-scale stainless-steel bioreactors without the complexity and cost of large industrial systems. Ideal for R&D, pilot runs and early-stage production.' },
    ],
  },
  {
    slug: 'benchtop-bioreactor-systems',
    old: 'https://new.belach.se/product/benchtop-bioreactor-systems/',
    category: 'bioreactors',
    name: 'Benchtop bioreactor systems',
    headline: 'For cell or microbial cultivation',
    figure: '1–3 L',
    card: 'Autoclavable Duran glass or stainless-steel bioreactors for early-stage R&D, standalone or 2–6 in parallel.',
    image: 'benchtop',
    gallery: ['benchtop', 'benchtop2'],
    meta: [['Working volume', '1–3 L'], ['Vessel', 'Duran glass or stainless steel'], ['Sterilization', 'Autoclavable'], ['Configuration', 'Standalone or 2–6 units']],
    intro: [
      'Available in Duran glass or stainless steel. These autoclave-sterilizable units are the standard for early-stage R&D and laboratory process optimization.',
    ],
    specs: [
      ['Vessel', 'Duran glass or stainless-steel bioreactor vessels, 1–3 L working volume. Stainless-steel lid with 12 standard Pg13.5 instrument ports and top stirrer'],
      ['Control tower', 'One control tower for each bioreactor, including all electronic components, 3 peristaltic pumps on the front, utility and instrument connections on the back for easy accessibility and cable/hose management'],
      ['Stirrer', 'Hygienic top stirrer (double mechanical seal), Rushton or pitch blade impeller, propeller'],
      ['Aeration', 'Applicable for aerobic/anaerobic cultivation, mass flow controlled, sterile filtered, off-gas cooling'],
      ['Temperature control', 'Electrical heating band, cooling finger'],
      ['Control', 'Stirrer speed, temperature, feeding rate, pH (by acid/base or CO₂), DO (by stirring, gas flow or feeding), antifoam/level'],
      ['Measurement', 'Exhaust gas analysis (O₂/CO₂), OD measurement'],
      ['Modules', 'Mass flow control of gas mix (air/O₂/CO₂), speed-controlled peristaltic pumps for feeding, on-off pumps for adding acid/base or antifoam, balance(s) for feed control'],
      ['Cleaning', 'Manual'],
      ['Sterilization', 'Autoclavable'],
      ['Software', 'BioPhantom© control software: monitoring and control of process parameters (advanced cascade control and sequences); process management with historical trends, alarm/event log, recipes and batch reports'],
      ['Configuration', 'Standalone or multiple 2–6 bioreactors (expandable)'],
      ['Options', 'Integration of 3rd-party instruments, perfusion device (ATF), OD measurement, precision feeding control'],
    ],
    sections: [],
  },
  {
    slug: 'pilot-scale-multi-parallel-bioreactors',
    old: 'https://new.belach.se/product/production-scale-multifermentors/',
    category: 'bioreactors',
    name: 'Pilot-scale multi-parallel bioreactors',
    headline: 'High-throughput, fully automated, flexible',
    figure: 'Up to 8 × 15 L',
    card: 'Up to 8 independent 5, 10 or 15 L bioreactors running simultaneously with full automation.',
    image: 'multiPilot',
    gallery: ['multiPilot'],
    meta: [['Volume per reactor', '5, 10 or 15 L'], ['Reactors', 'Up to 8'], ['Cleaning', 'Automatic CIP/SIP'], ['Control', 'BioPhantom© SCADA']],
    intro: [
      'Belach’s pilot-scale multi-parallel systems enable up to 8 independent bioreactors to operate simultaneously with full automation and process control. Designed for parallel experimentation and scale-up optimization, significantly accelerating time-to-market for new bioproducts.',
    ],
    specs: [
      ['Volumes', '5, 10 or 15 L per bioreactor'],
      ['Operation', 'Independent or synchronized'],
      ['Control', 'Advanced SCADA PC-based control with full automation'],
    ],
    sections: [
      { title: 'Key features', items: ['Independent process parameters per reactor', 'High-performance magnet-coupled stirrers', 'FDA/GMP-compliant materials', 'Automatic CIP/SIP, media feed and harvest sequences', 'Integration with optical biomass and off-gas analyzers'] },
      { title: 'BioPhantom© control', text: 'BioPhantom© supports multi-parallel process control, cascade DO regulation, recipe management and remote supervision.' },
      { title: 'Applications', text: 'Ideal for pilot-scale process optimization, microbial R&D and small-scale production environments.' },
      { title: 'Cleaning & sterilization', text: 'Fully automated CIP and SIP sequences ensure repeatable, sterile operations.' },
    ],
  },
  {
    slug: 'lab-scale-multi-parallel-bioreactors',
    old: 'https://new.belach.se/product/multifermentor-systems/',
    category: 'bioreactors',
    name: 'Lab-scale multi-parallel bioreactors',
    headline: 'High-throughput, fully automated, stainless steel 316L',
    figure: '6 × 0.2–1 L',
    card: 'Six independently controlled 316L reactors; up to 30 fermentations per week with one operator.',
    image: 'multiLab',
    gallery: ['multiLab'],
    meta: [['Volume per reactor', '0.2–1 L'], ['Reactors', '6'], ['Material', 'Stainless steel 316L'], ['Cleaning', 'Automated CIP/SIP']],
    intro: [
      'The lab-scale multi-parallel system offers six independently controlled reactors for microbial or cell cultivation, ideal for experimental design and downscaling studies.',
    ],
    specs: [
      ['Volumes', '0.2–1 L per bioreactor'],
      ['Material', 'Stainless steel 316L'],
      ['Operation', 'Fully automated CIP/SIP'],
      ['Control', 'BioPhantom© software with optical density and gas analysis options'],
    ],
    sections: [
      { title: 'Key features', items: ['Six individually controlled reactors', 'Magnetic stirrers ensure efficient sterile mixing', 'Automated calibration and optical density monitoring', 'Cascade DO control and gravimetric feed regulation', 'Up to 30 fermentations per week with one operator'] },
      { title: 'BioPhantom© control', text: 'BioPhantom© provides advanced control algorithms, multi-switch operations, automated calibration and open connectivity to LIMS/DoE systems.' },
      { title: 'Applications', text: 'Designed for high-throughput laboratory research and process development in microbial and cell culture biotechnology.' },
      { title: 'Cleaning & sterilization', text: 'Automated CIP and SIP enable single-operator efficiency and full sterility.' },
    ],
  },
  {
    slug: 'twin-biogas-reactor-system',
    old: 'https://new.belach.se/product/benchtop-biogas-reactor/',
    category: 'bioreactors',
    name: 'Automated twin biogas reactor system',
    headline: 'Flexible anaerobic digestion research',
    figure: '2 × 7–15 L',
    card: 'A fully automated platform for anaerobic digestion research with parallel reactors and precise gas monitoring.',
    image: 'biogas',
    gallery: ['biogas'],
    meta: [['Reactors', '2 × 7–15 L, expandable to 8'], ['Temperature', '55–78 °C'], ['Stirring', 'Top-mounted mechanical'], ['Medium', 'Up to 15 % solids']],
    intro: [
      'Belach’s twin biogas reactor system is a fully automated platform for anaerobic digestion research, ideal for academic and industrial applications requiring parallel operation and precise gas monitoring.',
    ],
    specs: [
      ['Reactors', '2 × 7–15 L (expandable to 8)'],
      ['Temperature', '55–78 °C'],
      ['Stirring', 'Top-mounted mechanical stirrer'],
      ['Medium', 'Up to 15 % solid content'],
    ],
    sections: [
      { title: 'Key features', items: ['Parallel reactor operation with independent control', 'Integrated volumetric gas counter and optional gas analyzer (CH₄, CO₂, O₂, H₂)', 'Automated BioPhantom© control of feeding, pH, temperature and gas output', 'Modular peristaltic pumps for feed, acid/base and antifoam dosing'] },
      { title: 'BioPhantom© control', text: 'Full automation, data logging and process parameter control via BioPhantom©, including trend analysis and alarm management.' },
      { title: 'Applications', text: 'Anaerobic process research, substrate optimization and two-stage digestion studies.' },
      { title: 'Cleaning & sterilization', text: 'Manual cleaning; optional autoclave sterilization for lab safety compliance.' },
    ],
  },
  {
    slug: 'airlift-bioreactors',
    old: 'https://new.belach.se/product/airlift-bioreactor/',
    category: 'bioreactors',
    name: 'Airlift bioreactors',
    headline: 'Gentle, efficient, fully controlled',
    figure: '3.5 L',
    card: 'Low-shear, air-driven mixing for filamentous and shear-sensitive cultures; up to six reactors per control unit.',
    image: 'airlift',
    gallery: ['airlift'],
    meta: [['Working volume', '3.5 L'], ['Vessel', 'Duran glass'], ['Agitation', 'Air-driven, no moving parts'], ['Operation', 'Continuous, semi-continuous or batch']],
    intro: [
      'Belach Bioteknik’s airlift bioreactors provide a reliable, low-shear solution for sensitive biological processes. Designed for R&D and pilot-scale use, these systems use air injection instead of mechanical agitation, ensuring homogeneous mixing with minimal stress on cells or organisms.',
    ],
    specs: [
      ['Working volume', '3.5 L'],
      ['Vessel material', 'Cylindrical Duran glass vessel'],
      ['Agitation', 'Air-driven circulation (no internal moving parts)'],
      ['Temperature control', 'Electrical heating bands'],
      ['Control system', 'Fully automated via BioPhantom© software'],
      ['Operation mode', 'Continuous, semi-continuous or batch'],
    ],
    sections: [
      { title: 'Key features', items: ['Air-driven agitation provides gentle, homogeneous mixing for filamentous or shear-sensitive cultures', 'Integrated sensors for temperature, pH, air flow, antifoam and level', 'Automated peristaltic pumps for feeding, acid/base and antifoam addition', 'Modular configuration allows operation of up to six bioreactors under one control unit', 'Compact design ideal for laboratory and pilot environments'] },
      { title: 'BioPhantom© control', text: 'The airlift bioreactors are fully managed through BioPhantom©, Belach’s SCADA-based control platform: precise regulation of air flow, pH and temperature, real-time process monitoring, automated feeding and data logging, designed to support FDA 21 CFR Part 11 compliance in GMP/GAMP environments.' },
      { title: 'Applications', items: ['Filamentous microorganism fermentation', 'Biological wastewater and sludge treatment', 'Single-cell protein production', 'Plant and animal cell cultivation', 'Process comparison and scale-up studies'] },
      { title: 'Cleaning & sterilization', text: 'Manual cleaning with autoclavable vessels provides secure, reproducible sterility between processes.' },
      { title: 'Optional modules', items: ['Additional peristaltic pumps for complex feeding strategies', 'Gas analysis module (O₂/CO₂) for real-time process tracking', 'Connection to a centralized BioPhantom© database for integrated data management'] },
    ],
  },
  {
    slug: 'enzymatic-hydrolysis-bioreactors',
    old: 'https://new.belach.se/product/enzymatic-hydrolysis-bioreactor/',
    category: 'bioreactors',
    name: 'Enzymatic hydrolysis bioreactors',
    headline: 'Robust, flexible, fully controlled',
    figure: '20–50 L',
    card: 'For enzymatic breakdown of low- and high-solid materials, up to 40 % solids, aerobic or anaerobic.',
    image: 'enzymatic',
    gallery: ['enzymatic'],
    meta: [['Working volume', '20–50 L'], ['Material', 'Stainless steel 316L'], ['Solid content', 'Up to 40 %'], ['Cleaning', 'Automated CIP/SIP']],
    intro: [
      'Belach Bioteknik’s enzymatic hydrolysis bioreactors are engineered for industrial and research applications involving the enzymatic breakdown of both low- and high-solid-content materials. Designed for flexibility and control, these systems handle solid contents up to 40 %, supporting both aerobic and anaerobic processes with precision and reproducibility.',
    ],
    specs: [
      ['Working volume', '20–50 L'],
      ['Vessel material', 'Stainless steel 316L, acid-resistant'],
      ['Stirring system', 'Bottom-mounted, double-sealed motor with anchor stirrer/scraper'],
      ['Temperature control', 'Jacketed vessel for heating and cooling via steam, hot water or cooling water'],
      ['Aeration', 'Mass-flow-controlled, sterile-filtered gas with off-gas cooling'],
      ['Automation', 'Fully automated BioPhantom© control for all process parameters'],
    ],
    sections: [
      { title: 'Key features', items: ['Handles high-solid-content materials efficiently with a unique tilting system for mixing', 'Supports both aerobic and anaerobic cultivation', 'Mass-flow gas control and precision feed pumps ensure optimal conditions', 'Integrated exhaust gas and optional optical density (OD) analysis', 'Anchor-type stirrer and scraper prevent clogging and maintain homogeneity', 'Available as standalone or multi-reactor configurations (2–6 units)'] },
      { title: 'BioPhantom© control', text: 'Precise control of stirrer speed, temperature, gas flow, DO, pH, feeding rate and antifoam, with recipe management, cascade control, historical trending, batch reporting and audit trails that support FDA 21 CFR Part 11 compliance.' },
      { title: 'Applications', items: ['Research and industrial development of enzymatic hydrolysis processes', 'High-solid-content biomass conversion (up to 40 %)', 'Aerobic and anaerobic fermentation studies', 'Food and feed biotechnology, biogas research and waste valorization'] },
      { title: 'Cleaning & sterilization', text: 'Automated cleaning-in-place (CIP) and steam-in-place (SIP) sequences ensure hygienic, repeatable operation and minimal downtime between runs.' },
      { title: 'Optional modules', items: ['Additional peristaltic pumps for customized feeding profiles', 'Gas composition analyzer (O₂, CO₂) for exhaust monitoring', 'Precision weighing balances for gravimetric feed control', 'Integration with external analyzers via open BioPhantom© connectivity'] },
    ],
  },
  {
    slug: 'web-based-bioreactor',
    old: 'https://new.belach.se/product/web-based-bioreactor/',
    category: 'bioreactors',
    draft: true, // not linked anywhere on the current site: confirm whether "ANT / WebAnt" is still offered
    name: 'Web-based bioreactor (ANT)',
    headline: 'Autoclavable fermentor with WebAnt compact controller',
    figure: '1 fermentor',
    card: 'Simple fermentation control with a web interface for a single fermentor.',
    image: 'webBased',
    gallery: ['webBased'],
    meta: [['Controller', 'SAIA PCD compact controller'], ['Interface', 'Web-based HMI'], ['Scope', 'Single fermentor'], ['Access', 'Any standard browser']],
    intro: ['WebAnt compact-controller-based simple fermentation control with web interface for a single fermentor.'],
    specs: [
      ['Controller', 'SAIA PCD compact controller'],
      ['Control', 'WebAnt control of the key bioprocess parameters (DO, pH, temperature, stirrer, feed)'],
      ['HMI', 'Web-based: control parameter access, data/history visualization, data export'],
      ['Access', 'Standard internet browsers (PC, tablet or mobile phone)'],
    ],
    sections: [],
  },

  /* ---------------- decontamination ---------------- */
  {
    slug: 'sink-type-eds',
    old: 'https://new.belach.se/product/sink-type-decontamination/',
    category: 'decontamination',
    name: 'Sink type EDS',
    headline: 'Standalone decontamination of small volumes of biological waste',
    figure: '500 L / day',
    card: 'Standalone, automatic decontamination for small amounts of biological waste in BSL 1, 2 and 3.',
    image: 'sinkEds',
    gallery: ['sinkEds'],
    meta: [['Batch volume', '42 L'], ['Daily capacity', '500 L'], ['Biosafety level', 'BSL 1, 2 and 3'], ['Control', 'PLC with touch panel']],
    intro: [
      'Sink type decontamination system is a standalone, automatic decontamination system for handling small amounts of biological waste in biosafety level 1, 2 and 3.',
    ],
    specs: [
      ['Batch volume', '42 L'],
      ['Daily capacity', '500 L'],
      ['Control', 'Robust, sequence-driven control system with industrial-standard PLC and touch panel'],
      ['Records', 'Process and alarm data'],
      ['Biosafety level', 'BSL 1, 2 and 3'],
      ['Design standard', 'EN 13311 / EN 13312'],
    ],
    sections: [],
  },
  {
    slug: 'external-decontamination-system',
    old: 'https://new.belach.se/product/external-decontamination-system/',
    category: 'decontamination',
    name: 'External decontamination system',
    headline: 'Safe, efficient, fully controlled',
    figure: '1000 L / day',
    card: 'Batch-wise sterilization of liquid biological waste from laboratories, hospital rooms and other BSL 1–3 facilities.',
    image: 'externalEds',
    gallery: ['externalEds'],
    meta: [['Batch volume', '42 L'], ['Buffer tank', '100–400 L'], ['Daily capacity', 'Up to 1000 L'], ['Sterilization', 'F₀ > 25']],
    intro: [
      'Belach Bioteknik’s external decontamination system (EDS) is designed for batch-wise sterilization of liquid biological waste from multiple sources, including microbiological laboratories, hospital rooms and other BSL 1–3 facilities.',
    ],
    specs: [
      ['Batch process', 'Treats collected waste in 42 L batches with a 100–400 L buffering tank. Daily capacity up to 1000 L'],
      ['Sterilization guarantee', 'Heat treatment ensures F₀ > 25, providing safe and effective inactivation of all microorganisms'],
      ['Control & monitoring', 'Sequence-driven industrial PLC with touch panel; records process parameters and alarms for secure, reliable operation'],
      ['Compliance', 'Designed according to EN 13311 / EN 13312'],
    ],
    sections: [
      { title: 'Why choose Belach external decontamination systems', items: ['Safely and efficiently treat liquid biohazard waste from multiple sources', 'Fully controlled, automated process for minimal operator intervention', 'Robust, compliant design built for BSL 1–3 environments'] },
    ],
  },
  {
    slug: 'pilot-eds-dual-vessels',
    old: 'https://new.belach.se/product/pilot-eds-dual-vessels/',
    category: 'decontamination',
    name: 'Pilot EDS (dual vessels)',
    headline: 'Two synchronized kill tanks, sized to your capacity',
    figure: '1000–2000 L',
    card: 'Batch-mode heat treatment in two synchronized kill tanks, up to 137 °C, for vaccine research and manufacturing.',
    image: 'pilotEds',
    gallery: ['pilotEds'],
    meta: [['Unit volume', 'Typically 1000–2000 L'], ['Kill tanks', '2, working in tandem'], ['Temperature', 'Up to 137 °C'], ['Sterilization', 'F₀ > 25']],
    intro: [
      'The Pilot EDS (dual vessels) operates in batch mode, utilizing two synchronized kill tanks. The heat treatment process, capable of reaching up to 137 °C, guarantees sterilization with F₀ > 25, fully meeting the most stringent biosafety requirements.',
      'The system capacity typically ranges between 1000 and 2000 litres; each unit is individually designed and manufactured according to the customer’s specific capacity needs, so the Pilot EDS fits seamlessly into the research or production environment.',
    ],
    specs: [
      ['Operation', 'Batch-wise, two parallel kill tanks working in tandem'],
      ['Unit volume', 'Typically 1000–2000 L, based on user requirements'],
      ['Heat treatment', 'Up to 137 °C; guarantees F₀ > 25 sterilization'],
      ['Control', 'Sequence-driven industrial-standard PLC with touch-screen interface'],
      ['Records', 'All process and alarm data recorded automatically'],
      ['Biosafety level', 'BSL 1, 2 and 3'],
    ],
    sections: [
      { title: 'Built for', text: 'Liquid biological waste from multiple sources, such as virus vaccine research or manufacturing facilities. Automatic recording of all process and alarm data provides full transparency, operational safety and audit readiness.' },
    ],
  },

  /* ---------------- control systems ---------------- */
  {
    slug: 'biophantom-control',
    old: 'https://new.belach.se/product/bio-phantom-control/',
    category: 'control',
    name: 'BioPhantom© Control',
    headline: 'One SCADA platform from lab reactor to production',
    figure: '1–8 bioreactors',
    card: 'Open-connectivity SCADA software for MS Windows with advanced control loops, designed to support FDA 21 CFR Part 11 compliance.',
    image: 'bioPhantom',
    gallery: ['bioPhantom', 'bioPhantom2', 'bioPhantom3', 'bioPhantom4'],
    meta: [['Bioreactors per PC', '1–8'], ['Platform', 'MS Windows, MS SQL Server'], ['Compliance', 'Supports FDA 21 CFR Part 11'], ['Processes', 'Microbial and cell culture']],
    intro: [
      'BioPhantom Control is an open-connectivity industrial software platform designed for MS Windows PCs. It offers a consistent look-and-feel and harmonized control functions across the full bioprocess range, from small lab reactors to pilot-scale production bioreactors, facilitating smooth scale-up. Specific functions are available for both microbial and cell culture applications.',
      'The software is designed to support FDA 21 CFR Part 11 compliance, with audit trail, secure data logging and batch reports, and all BioPhantom control applications are customized to meet the unique needs of each customer.',
    ],
    specs: [
      ['Control loops', 'PID, GAP and custom cascade control algorithms for measured and calculated values'],
      ['Sequences', 'Flexible sequential control with configurable action triggers, time profiles and trigger functions'],
      ['Capacity', '1–8 bioreactors on a single PC'],
      ['Data', 'Central database; flexible data logging and trend comparison, including offline data'],
      ['Connectivity', 'Open database connectivity with interface to LIMS and DoE modules'],
      ['Compliance', 'Designed to support FDA 21 CFR Part 11 and GMP/GAMP environments'],
    ],
    sections: [
      { title: 'Monitoring & control', items: ['Connect 1–8 bioreactors to a single PC', 'Real-time monitoring of all critical process variables', 'Live and historical data display with dynamic, interactive graphics', 'PID, GAP and custom cascade control algorithms for measured and calculated values', 'Interactive operation with control sequences, time profiles and trigger functions'] },
      { title: 'Process management', items: ['Flexible data logging and trend comparison, including integration of offline data', 'Remote process access via local network, telephone or internet', 'Prioritized alarm system with automated emergency sequences', 'Operator event logging and searchable audit trail', 'Detailed batch reports with operator notes', 'Multi-level password protection for secure access', 'Open database connectivity with seamless interface to LIMS and DoE modules'] },
      { title: 'Key benefits', items: ['<strong>Seamless scalability:</strong> same platform from lab to pilot scale', '<strong>Customizable:</strong> tailored to the specific needs of each bioprocess', '<strong>Intuitive operation:</strong> minimizes training time and operational errors', '<strong>Secure and auditable:</strong> designed to support FDA 21 CFR Part 11 compliance', '<strong>Advanced data management:</strong> central database for complete transparency', '<strong>Remote access:</strong> monitor and manage your processes from anywhere', '<strong>Integration-ready:</strong> easily connects to third-party systems and LIMS'] },
    ],
  },
  {
    slug: 'bio-pilot-control',
    old: 'https://new.belach.se/product/bio-pilot/',
    category: 'control',
    name: 'Bio-Pilot Control',
    headline: 'Integrated control for complete bioprocess plants',
    figure: 'ISA S88',
    card: 'Integrated control of bioreactors, bulk tanks, transfer lines, CIP/SIP and waste decontamination stations.',
    image: 'bioPilot',
    gallery: ['bioPilot'],
    meta: [['Scope', 'Plant-wide'], ['Batch management', 'ISA S88'], ['Data', 'MS SQL Server, supports 21 CFR Part 11'], ['Integration', 'ERP / MES']],
    intro: [
      'Bio-Pilot Control integrates bioreactors, bulk tanks, transfer lines and downstream processing equipment in one control system, with master-slave operator stations in a Windows PC network.',
    ],
    specs: [
      ['Scope', 'Integrated control of bioreactors, bulk tanks, transfer lines and downstream processing equipment'],
      ['Automation', 'Automated CIP/SIP processes; automated waste decontamination stations'],
      ['Architecture', 'Master-slave operator stations in Windows PC-network architecture'],
      ['Batch management', 'ISA S88 compliant, flexible batch management system'],
      ['Data', 'Electronic data handling in an MS SQL Server database, designed to support FDA 21 CFR Part 11 compliance'],
      ['Integration', 'Interfacing to ERP or MES systems'],
    ],
    sections: [],
  },
  {
    slug: 'bel-iot-control',
    old: 'https://new.belach.se/product/bel-iot/',
    category: 'control',
    name: 'Bel-IoT Control',
    headline: 'Secure cloud access from a smartphone or tablet',
    figure: '1–6 bioreactors',
    card: 'A soft PLC with an IoT Communicator: operators access the control system securely through the cloud.',
    image: 'belIot',
    gallery: ['belIot'],
    meta: [['Bioreactors', '1–6'], ['Access', 'Cloud: smartphone, tablet'], ['Core', 'Soft PLC + IoT Communicator'], ['Data', 'LIMS / DoE interface']],
    intro: [
      'Bel-IoT Control is a combination of a powerful soft PLC and an IoT Communicator application. Operators using their smartphones or tablets can access the control system securely through the cloud. Bel-IoT Control provides advanced control loops for bioprocess parameter regulation, flexible sequential control, configurable action triggering and a user-friendly graphical HMI through the internet. The system provides all essential process management functions.',
    ],
    specs: [
      ['Bioreactors', '1–6 connected to the cloud'],
      ['Control loops', 'PID, GAP and custom cascade control algorithms for measured and calculated process values'],
      ['HMI', 'User-friendly graphical HMI through the internet'],
      ['Security', 'Multi-level password security'],
    ],
    sections: [
      { title: 'Monitoring & control', items: ['Connect 1–6 bioreactors to the cloud', 'Real-time monitoring of process variables', 'Live and historical data display in dynamic graphics', 'PID, GAP and custom cascade control algorithms for measured and calculated process values', 'User-friendly, interactive operation'] },
      { title: 'Process management', items: ['Safe process data logging', 'Cloud-based remote access through portable devices', 'Prioritized alarm system with emergency sequences', 'Simple experimental protocols; multi-level password security', 'Open database connectivity and interface to LIMS and DoE module'] },
    ],
  },

  /* ---------------- rental ---------------- */
  {
    slug: 'rental-bioreactor-100-l',
    old: 'https://new.belach.se/product/stainless-steel-in-situ-sterilizable-bioreactor-for-cell-cultivation-100l/',
    category: 'rental',
    name: '100 L cell culture bioreactor',
    headline: 'Stainless-steel, in-situ sterilizable, for rent',
    figure: '100 L',
    card: 'Stainless-steel in-situ sterilizable bioreactor for cell cultivation.',
    image: 'rental100',
    gallery: ['rental100'],
    meta: [['Volume', '100 L'], ['Vessel', 'Stainless steel'], ['Sterilization', 'In situ'], ['Use', 'Cell cultivation']],
    intro: ['Stainless-steel in-situ sterilizable bioreactor for cell cultivation, 100 L. Send us a message for further information.'],
    specs: [],
    sections: [],
  },
  {
    slug: 'rental-bioreactor-26-l',
    old: 'https://new.belach.se/product/stainless-steel-in-situ-sterilizable-bioreactor-for-cell-cultivation-26l-20l-wv/',
    category: 'rental',
    draft: true, // only in the sitemap on the current site: confirm it is still available
    name: '26 L cell culture bioreactor (20 L wv)',
    headline: 'Stainless-steel, in-situ sterilizable, for rent',
    figure: '26 L',
    card: '20 L working volume, bottom magnetic coupled stirrer, load cells, BioPhantom© SIP.',
    image: 'rental26',
    gallery: ['rental26'],
    meta: [['Total / working volume', '26 L / 20 L'], ['Stirrer', 'Bottom magnetic, max. 300 rpm'], ['Sterilization', 'Automated SIP'], ['Control', 'BioPhantom©']],
    intro: ['Stainless-steel in-situ sterilizable bioreactor for cell cultivation, 26 L (20 L working volume).'],
    specs: [
      ['Vessel', '20 L wv stainless-steel vessel with bottom magnetic coupled stirrer (max. 300 rpm), stainless-steel frame with thermo-system, sterile filters and load cells'],
      ['Instrumentation', 'Pg13.5 ports for DO, pH sensors and outlet gas analyzer'],
      ['Pumps', 'Peristaltic pumps for acid/base/antifoam and feeding'],
      ['Gas', 'Mass flow controller (optional)'],
      ['Automation', 'Automated sterilization in place and optional cleaning-in-place with BioPhantom© advanced control system'],
      ['Documentation', 'Equipment description and operator manual available'],
    ],
    sections: [],
  },
  {
    slug: 'rental-bioreactor-10-l',
    old: 'https://new.belach.se/product/stainless-steel-in-situ-bioreactor-for-cell-cultivation-10l-7l-wv/',
    category: 'rental',
    name: '10 L cell culture bioreactor (7 L wv)',
    headline: 'Stainless-steel, in-situ sterilizable, for rent',
    figure: '10 L',
    card: '7 L working volume, bottom magnetic coupled stirrer, automated SIP with BioPhantom©.',
    image: 'rental10',
    gallery: ['rental10'],
    meta: [['Total / working volume', '10 L / 7 L'], ['Stirrer', 'Bottom magnetic, max. 300 rpm'], ['Sterilization', 'Automated SIP'], ['Control', 'BioPhantom©']],
    intro: ['Stainless-steel in-situ bioreactor for cell cultivation, 10 L (7 L working volume).'],
    specs: [
      ['Vessel', '7 L wv stainless-steel vessel with bottom magnetic coupled stirrer (max. 300 rpm), stainless-steel frame with thermo-system, sterile filters'],
      ['Instrumentation', 'Pg13.5 ports for DO, pH sensors and outlet gas analyzer'],
      ['Pumps', 'Peristaltic pumps for acid/base/antifoam and feeding'],
      ['Gas', 'Mass flow controllers (optional) for air/O₂'],
      ['Automation', 'Automated sterilization in place and optional cleaning-in-place with BioPhantom© advanced control system'],
      ['Documentation', 'Equipment description and operator manual available'],
    ],
    sections: [],
  },
];

export const published = products.filter((p) => !p.draft);
export const byCategory = (id) => published.filter((p) => p.category === id);
export const bySlug = (slug) => products.find((p) => p.slug === slug);
